# version: '3.8'

services:
  # Item service that lists available items with their prices
  item:
    restart: always
    build:
      context: ./items
    ports:
      - '3001:80'
    volumes:
      - ./items:/var/www/html
    depends_on:
      - itemdb
    networks:
      - gaworkshop
      - shopmany

  itemdb:
    image: mysql:5.7.25
    platform: linux/amd64  # Specify platform
    restart: always
    environment:
      MYSQL_DATABASE: 'shopmany'
      MYSQL_USER: 'hello'
      MYSQL_PASSWORD: 'ciao'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - ./items/db.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - gaworkshop
      - shopmany

  # Discount service that manages item discounts
  discount:
    image: node:10.15.3-stretch
    platform: linux/amd64  # Specify platform
    working_dir: /usr/src/app
    volumes:
      - ./discount:/usr/src/app
    command: ["node", "./server.js"]
    ports:
      - '3003:3000'
    depends_on:
      - discountdb
    networks:
      - gaworkshop
      - shopmany

  discountdb:
    image: mongo:4.0.6-xenial
    platform: linux/amd64  # Specify platform
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "shopmany"
    ports:
      - '27017:27017'
    volumes:
      - ./discount/init:/docker-entrypoint-initdb.d
    networks:
      - gaworkshop
      - shopmany

  # Pay service that handles item purchases
  pay:
    build:
      context: ./pay
    ports:
      - '3002:8080'
    networks:
      - gaworkshop
      - shopmany
    depends_on:
      - paydb

  paydb:
    image: mysql:5.7.25
    platform: linux/amd64  # Specify platform
    restart: always
    environment:
      MYSQL_DATABASE: 'pay'
      MYSQL_USER: 'howdy'
      MYSQL_PASSWORD: 'hellohello'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - ./pay/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - gaworkshop
      - shopmany

  # Frontend UI service
  frontend:
    image: golang:1.14.0-stretch
    platform: linux/amd64  # Specify platform
    command: ["go", "run", "-mod", "vendor", "./main.go"]
    ports:
      - '3000:3000'
    volumes:
      - "./frontend:/opt/app"
    working_dir: "/opt/app"
    depends_on:
      - item
      - pay
      - discount
    networks:
      - gaworkshop
      - shopmany

networks:
  shopmany:
  gaworkshop:
    external: true
